INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 1, 'Nový rok');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 2, 'Alexandra, Karina');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 3, 'Daniela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 5, 'Andrea');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 7, 'Bohuslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 9, 'Alexej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 10, 'Dáša');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 12, 'Ernest');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 13, 'Rastislav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 14, 'Radovan');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 15, 'Dobroslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 16, 'Kristína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 17, 'Nataša');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 18, 'Bohdana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 19, 'Drahomíra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 20, 'Dalibor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 21, 'Vincent');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 22, 'Zora');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 23, 'Miloš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 24, 'Timotej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 25, 'Gejza');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 26, 'Tamara');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 27, 'Bohuš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 28, 'Alfonz');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 29, 'Gašpar');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 30, 'Ema');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 31, 'Emil');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 4, 'Drahoslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 6, 'Antónia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 8, 'Severín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (1, 11, 'Malvína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 2, 'Erik, Erika');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 1, 'Tatiana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 3, 'Blažej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 4, 'Veronika');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 6, 'Dorota');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 7, 'Vanda');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 9, 'Zdenko');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 10, 'Gabriela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 11, 'Dezider');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 12, 'Perla');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 13, 'Arpád');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 15, 'Pravoslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 16, 'Ida, Liana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 17, 'Miloslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 19, 'Vlasta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 20, 'Lívia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 21, 'Eleonóra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 22, 'Etela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 23, 'Roman, Romana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 24, 'Matej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 25, 'Frederik, Frederika');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 26, 'Viktor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 27, 'Alexander');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 29, 'Radomír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 5, 'Agáta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 8, 'Zoja');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 14, 'Valentín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 18, 'Jaromír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (2, 28, 'Zlatica');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 1, 'Albín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 2, 'Anežka');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 3, 'Bohumil');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 5, 'Fridrich');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 7, 'Tomáš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 9, 'Františka');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 10, 'Branislav, Bruno');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 11, 'Angela, Angelika');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 12, 'Gregor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 13, 'Vlastimil');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 14, 'Matilda');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 16, 'Boleslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 18, 'Eduard');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 21, 'Blahoslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 23, 'Adrián');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 25, 'Marián');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 26, 'Emanuel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 27, 'Alena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 30, 'Vieroslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 4, 'Kazimír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 6, 'Radoslav, Radoslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 8, 'Alan, Alana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 15, 'Svetlana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 19, 'Jozef');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 24, 'Gabriel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 29, 'Miroslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (3, 31, 'Benjamín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 2, 'Zita');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 1, 'Hugo');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 3, 'Richard');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 4, 'Izidor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 5, 'Miroslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 6, 'Irena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 7, 'Zoltán');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 9, 'Milena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 10, 'Igor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 11, 'Július');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 12, 'Estera');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 13, 'Aleš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 16, 'Dana, Danica');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 17, 'Rudolf, Rudolfa');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 18, 'Valér');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 19, 'Jela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 20, 'Marcel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 21, 'Ervín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 22, 'Slavomír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 23, 'Vojtech');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 25, 'Marek');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 26, 'Jaroslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 27, 'Jaroslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 28, 'Jarmila');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 29, 'Lea');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 30, 'Anastázia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 8, 'Albert');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 14, 'Justína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 15, 'Fedor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (4, 24, 'Juraj');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 2, 'Žigmund');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 1, 'Sviatok práce');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 4, 'Florián');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 5, 'Lesana, Lesia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 6, 'Hermína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 7, 'Monika');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 9, 'Roland');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 10, 'Viktória');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 11, 'Blažena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 12, 'Pankrác');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 17, 'Gizela, Aneta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 22, 'Júlia, Juliána');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 25, 'Urban');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 27, 'Iveta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 29, 'Vilma');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 30, 'Ferdinand');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 31, 'Petrana, Petronela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 3, 'Galina, Timea');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 8, 'Ingrida');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 13, 'Servác');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 14, 'Bonifác');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 15, 'Žofia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 16, 'Svetozár');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 18, 'Viola');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 19, 'Gertrúda');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 20, 'Bernard');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 21, 'Zina');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 23, 'Želmíra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 24, 'Ela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 26, 'Dušan');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (5, 28, 'Viliam');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 1, 'Žaneta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 2, 'Oxana, Xénia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 3, 'Karolína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 5, 'Laura');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 6, 'Norbert');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 8, 'Medard');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 9, 'Stanislava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 10, 'Margaréta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 11, 'Dobroslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 15, 'Vít');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 16, 'Bianka, Blanka');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 21, 'Alojz');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 22, 'Paulína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 23, 'Sidónia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 24, 'Ján');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 25, 'Tadeáš, Olívia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 26, 'Adriána');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 27, 'Ladislav, Ladislava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 29, 'Peter, Pavol, Petra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 4, 'Lenka');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 7, 'Róbert, Róberta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 12, 'Zlatko');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 13, 'Anton');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 14, 'Vasil');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 17, 'Adolf');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 18, 'Vratislav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 19, 'Alfréd');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 20, 'Valéria');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 28, 'Beáta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (6, 30, 'Melánia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 2, 'Berta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 3, 'Miloslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 4, 'Prokop');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 6, 'Patrik, Patrícia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 5, 'Cyril, Metod');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 7, 'Oliver');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 8, 'Ivan');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 9, 'Lujza');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 10, 'Amália');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 12, 'Nina');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 14, 'Kamil');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 15, 'Henrich');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 16, 'Drahomír, Karmela, Rút');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 17, 'Bohuslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 19, 'Dušana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 21, 'Daniel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 22, 'Magdaléna');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 25, 'Jakub, Timur');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 26, 'Anna, Hana, Anita');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 27, 'Božena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 28, 'Krištof');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 30, 'Libuša');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 31, 'Ignác');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 1, 'Diana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 11, 'Milota');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 13, 'Margita');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 18, 'Kamila');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 24, 'Vladimír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (7, 29, 'Marta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 2, 'Gustáv');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 1, 'Božidara');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 3, 'Jerguš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 5, 'Hortenzia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 7, 'Štefánia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 10, 'Vavrinec');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 11, 'Zuzana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 12, 'Darina');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 15, 'Marcela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 16, 'Leonard');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 17, 'Milica');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 18, 'Elena, Helena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 19, 'Lýdia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 20, 'Anabela, Liliana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 21, 'Jana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 23, 'Filip');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 24, 'Bartolomej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 27, 'Silvia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 28, 'Augustín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 29, 'Nikola, Nikolaj');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 30, 'Ružena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 4, 'Dominik, Dominika');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 6, 'Jozefína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 8, 'Oskar');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 14, 'Mojmír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 22, 'Tichomír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 26, 'Samuel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (8, 31, 'Nora');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 1, 'Arnold');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 2, 'Levoslav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 4, 'František');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 5, 'Viera');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 6, 'Natália');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 7, 'Eliška');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 8, 'Brigita');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 9, 'Dionýz');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 10, 'Slavomíra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 12, 'Maximilián');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 17, 'Hedviga');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 22, 'Sergej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 24, 'Kvetoslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 25, 'Aurel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 27, 'Sabína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 30, 'Šimon, Simona');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 31, 'Aurélia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 3, 'Stela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 11, 'Valentína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 13, 'Koloman');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 14, 'Boris');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 15, 'Terézia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 16, 'Vladimíra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 18, 'Lukáš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 19, 'Kristián');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 20, 'Vendelín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 23, 'Alojzia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 26, 'Demeter');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 28, 'Dobromila');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 29, 'Klára');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 2, 'Bibiána');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 1, 'Edmund');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 3, 'Oldrich');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 4, 'Barbora, Barbara');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 5, 'Oto');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 6, 'Mikuláš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 7, 'Ambróz');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 9, 'Izabela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 10, 'Radúz');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 11, 'Hilda');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 12, 'Otília');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 16, 'Albína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 17, 'Kornélia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 18, 'Sláva');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 19, 'Judita');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 20, 'Dagmara');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 22, 'Adela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 26, 'Štefan');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 27, 'Filoména');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 28, 'Ivana, Ivona');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 29, 'Milada');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 30, 'Dávid');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 31, 'Silvester');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 8, 'Marína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 13, 'Lucia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 14, 'Branislava, Bronislava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 15, 'Ivica');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 21, 'Bohdan');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (12, 24, 'Adam, Eva');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 1, 'Drahoslava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 5, 'Regína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 6, 'Alica');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 7, 'Marianna');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 9, 'Martina');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 10, 'Oleg');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 12, 'Mária, Marlena');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 17, 'Olympia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 19, 'Konštantín');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 22, 'Móric');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 23, 'Zdenka');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 25, 'Vladislav, Vladislava');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 27, 'Cyprián, Damián');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 28, 'Václav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 29, 'Michal, Michaela');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 30, 'Jarolím');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 2, 'Linda, Rebeka');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 3, 'Belo');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 4, 'Rozália');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 8, 'Miriama');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 11, 'Bystrík');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 13, 'Ctibor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 15, 'Jolana');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 18, 'Eugénia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 21, 'Matúš');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (9, 26, 'Edita');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 1, 'Denis, Denisa');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 3, 'Hubert');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 4, 'Karol');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 6, 'Renáta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 7, 'René');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 9, 'Teodor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 10, 'Tibor');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 11, 'Maroš, Martin');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 12, 'Svätopluk');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 13, 'Stanislav');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 14, 'Irma');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 15, 'Leopold');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 16, 'Agnesa');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 17, 'Klaudia');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 18, 'Eugen');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 19, 'Alžbeta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 20, 'Félix');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 22, 'Cecília');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 23, 'Klement');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 24, 'Emília');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 25, 'Katarína');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 27, 'Milan');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 2, 'Pamiatka zosnulých');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 5, 'Imrich');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 8, 'Bohumír');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 21, 'Elvíra');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 26, 'Kornel');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 28, 'Henrieta');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 29, 'Vratko');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (11, 30, 'Andrej, Ondrej');
INSERT INTO ziackaknizka.calendar (month, day, name) VALUES (10, 21, 'Uršula');
